server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092

kafka-topic-names:
  avro: "avro-serializer-topic"
  string: "string-serializer-topic"
  custom: "custom-serializer-topic"

kafka-consumer:
  avro-consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    group-id: "avro-consumer-group"
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: "true"
  string-consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group-id: "string-consumer-group"
  custom-consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: com.example.kafkaconsumerresearch.config.TestDtoDeserializer
    group-id: "custom-consumer-group"